# Site settings
title: Jekyll Guide Theme
email:
description: "A Jekyll theme in the style of documentation."
baseurl: "/jekyll-guide-theme" # the subpath of your site, e.g. /blog
url: "http://wolfenshadows.github.io/jekyll-guide-theme/" # the base hostname & protocol for your site
twitter_username:
github_username:
disqus_username:

google_analytics_id:
collections:
  collection:
    name: Collection
    output: true
    permalink: "/:collection/:title/"
defaults:
  - scope:
      path: ""
      type: collection1
    values:
      layout: docs
url: http://jekyll.tips
